import dash_bootstrap_components as dbc
import dash
from dash import html, dcc

navbar = dbc.NavbarSimple(
    children=[
        dbc.NavItem(dbc.NavLink("Home", href="/")),
        dbc.DropdownMenu(
            children=[
                dbc.DropdownMenuItem("More pages", header=True),
                dbc.DropdownMenuItem("movement1", href="/movement1"),#, external_link=True,),
                dbc.DropdownMenuItem("movement2", href="#"),
            ],
            nav=True,
            in_navbar=True,
            label="More",
        ),
    ],
    brand="DigitalAIArtGallery",
    color="primary",
    dark=True,
    fixed="top",
)

app = dash.Dash(__name__, use_pages=True, external_stylesheets=[dbc.themes.CYBORG])
server = app.server
app.layout = dbc.Container([
	dbc.Row([
		dbc.Col([
			html.H1('Welcome to the AI Generated Digital Art Gallery!', style={'textAlign': 'center', 'padding-top':'70px'}),
        		html.Div(children='''
                		Artworks generated by using X model categorized by movements.
        		''', style={'textAlign': 'center'}),
			]),

	]),
	html.Hr(),
	navbar,
	dash.page_container,
])


if __name__ == '__main__':
	app.run_server(debug=True, use_reloader=True) # Turn off reloader if inside Jupyter


